export const LARK_BLOCK_TYPE_NAME: Readonly<Record<number, string>> = {
  1: 'Page',
  2: 'Text',
  3: 'Heading1',
  4: 'Heading2',
  5: 'Heading3',
  6: 'Heading4',
  7: 'Heading5',
  8: 'Heading6',
  9: 'Heading7',
  10: 'Heading8',
  11: 'Heading9',
  12: 'Bullet',
  13: 'Ordered',
  14: 'Code',
  15: 'Quote',
  16: 'MentionDoc',
  17: 'TodoList',
  18: 'Bitable',
  19: 'Callout',
  20: 'ChatCard',
  21: 'Diagram',
  22: 'Divider',
  23: 'File',
  24: 'Grid',
  25: 'GridColumn',
  26: 'Iframe',
  27: 'Image',
  28: 'Widget',
  29: 'MindNote',
  30: 'Sheet',
  31: 'Table',
  32: 'TableCell',
  33: 'View',
  34: 'QuoteContainer',
  40: 'AddOns',
  43: 'Board',
  999: 'SyncedBlock',
};

export function getLarkBlockTypeName(blockType: number): string {
  return LARK_BLOCK_TYPE_NAME[blockType] ?? `Unknown(${blockType})`;
}
